### ISSUE TITLE
日志

### ISSUE THREAD

**Issue by xlingzzy** [heinu123/whitelist#7]
whitelist.service - proxy whitelist
   Loaded: loaded (/etc/systemd/system/whitelist.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2023-03-08 07:22:26 UTC; 2s ago
     Docs: https://github.com/heinu123/whitelist
  Process: 10199 ExecStart=/usr/bin/python3 /usr/whitelist/main.py (code=exited, status=1/FAILURE)
 Main PID: 10199 (code=exited, status=1/FAILURE)
Mar 08 07:22:26 VM3764059907CD644 systemd[1]: whitelist.service: Main process exited, code=exited, status=1/FAILURE
Mar 08 07:22:26 VM3764059907CD644 systemd[1]: whitelist.service: Failed with result 'exit-code'.

**Comment by heinu123** [comment]
删除配置文件重新初始化

**Comment by xlingzzy** [comment]
好了  现在前台可以正常运行  Ctrl+c后  用
nohup python3 -u main.py > log.out 2>&1 &
这段命令 后台也启动不了
